### Глава 12 - Обработка ошибок и исключения

### Примеры из книги

##### Создание собственных исключений

* [Пример](examples/myself/InheritingException.java) - Создание собственного исключения
* [Пример](examples/myself/FullConstructors.java) - Создание собственного исключения с аргументом в конструкторе

### Упражнения

* [1](exercises/ex1/MainApp.java) - Создайте класс с методом `main()`, возбуждающим исключение типа `Exception` из блока `try`. Задайте в
конструкторе для `Exception` строковый аргумент. Перехватите исключение в блоке `catch` и распечатайте текст аргумента.
Добавьте блок `finally` и выведите сообщение как доказательство его выполнения.
* [2](exercises/ex2/MainApp.java) - Определите ссылку на объект и присвойте ей значение `null`. Попробуйте вызвать
метод объекта, пользуясь этой ссылкой. Потом вставьте этот код в блок `try-catch` и перехватите исключение.
* [3](exercises/ex3/MainApp.java) - Напишите код, который генерирует и перехватывает исключение
`ArrayIndexOutOfBoundsException`.
* [4](exercises/ex4/MainApp.java) - Создайте ваш собственный класс исключения, используя ключевое слово `extends`.
Напишите конструктор, получающий строковый аргумент, и сохраните этот аргумент внутри объекта по ссылке на `String`.
Напишите метод, который выводит эту строку. Подсоедините новый блок `try-catch` для проверки нового исключения.
* [5](exercises/ex5/MainApp.java) - Создайте собственную реализацию модели возобновления, используя цикл `while`,
который выполняется до тех пор, пока исключение не перестанет выполняться.


